(() => {
  'use strict';
  const $ = s => document.querySelector(s), cfg=window.RADKO_CONFIG||{};
  let db, products=[];
  const message=(id,text)=>{$(id).textContent=text;};
  function loadSdk(){return new Promise((resolve,reject)=>{if(window.supabase?.createClient)return resolve();const script=document.createElement('script');script.src='https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2';script.onload=()=>window.supabase?.createClient?resolve():reject(new Error('Не удалось загрузить библиотеку Supabase'));script.onerror=()=>reject(new Error('Не удалось загрузить библиотеку Supabase'));document.head.append(script);});}
  async function authorized(){const {data:{user},error}=await db.auth.getUser();if(error||!user)return false;const {data,error:roleError}=await db.from('admin_users').select('id').eq('id',user.id).maybeSingle();if(roleError)throw roleError;return !!data;}
  async function refreshAuth(){try{const okay=await authorized();$('#login-panel').classList.toggle('admin-hidden',okay);$('#admin-panel').classList.toggle('admin-hidden',!okay);if(okay)await Promise.all([loadProducts(),loadOwner()]);}catch(e){message('#product-message',`Ошибка доступа: ${e.message}`);}}
  async function uploadImage(file,prefix){if(!file)return null;const allowed=['image/jpeg','image/png','image/webp'];if(!allowed.includes(file.type)||file.size>3*1024*1024)throw new Error('Нужен JPG, PNG или WebP размером до 3 МБ.');const ext={'image/jpeg':'jpg','image/png':'png','image/webp':'webp'}[file.type];const path=`${prefix}/${crypto.randomUUID()}.${ext}`;const {error}=await db.storage.from('images').upload(path,file,{contentType:file.type,upsert:false,cacheControl:'3600'});if(error)throw error;const {data}=db.storage.from('images').getPublicUrl(path);return data.publicUrl;}
  function clearForm(){ $('#product-form').reset();$('#product-id').value='';$('#product-available').checked=true;$('#product-active').checked=true;$('#product-save').textContent='Сохранить товар'; }
  function editProduct(p){$('#product-id').value=p.id;for(const code of ['ar','en','ru']){$(`#name-${code}`).value=p[`name_${code}`]||'';$(`#description-${code}`).value=p[`description_${code}`]||'';}$('#product-category').value=p.category;$('#product-price').value=p.price??'';$('#product-available').checked=p.available;$('#product-active').checked=p.active;$('#product-image').value='';$('#product-save').textContent='Сохранить изменения';$('#product-form').scrollIntoView({behavior:'smooth',block:'start'});}
  async function loadProducts(){const {data,error}=await db.from('products').select('*').order('created_at',{ascending:false});if(error)throw error;products=data||[];const box=$('#admin-products');box.replaceChildren();if(!products.length){box.textContent='Пока нет товаров.';return;}for(const p of products){const row=document.createElement('div');row.className='admin-product-row';const text=document.createElement('span');text.textContent=`${p.name_ru||p.name_ar} · ${p.price===null?'цена по запросу':p.price+' EGP'}${p.active?'':' · скрыт'}`;const actions=document.createElement('div');const edit=document.createElement('button');edit.textContent='Изменить';edit.type='button';edit.addEventListener('click',()=>editProduct(p));const del=document.createElement('button');del.textContent='Удалить';del.type='button';del.addEventListener('click',async()=>{if(!confirm(`Удалить «${p.name_ru||p.name_ar}»?`))return;const {error}=await db.from('products').delete().eq('id',p.id);if(error)message('#product-message',`Ошибка: ${error.message}`);else{clearForm();await loadProducts();message('#product-message','Товар удалён.');}});actions.append(edit,del);row.append(text,actions);box.append(row);}}
  async function loadOwner(){const {data,error}=await db.from('site_settings').select('*').eq('id',1).maybeSingle();if(error)throw error;if(!data)return;for(const code of ['ar','en','ru'])$(`#owner-${code}`).value=data[`owner_name_${code}`]||'';if(data.owner_photo_url){$('#owner-preview').src=data.owner_photo_url;$('#owner-preview').hidden=false;}}
  $('#login-form').addEventListener('submit',async e=>{e.preventDefault();const btn=e.submitter;btn.disabled=true;try{const {error}=await db.auth.signInWithPassword({email:$('#login-email').value.trim(),password:$('#login-password').value});if(error)throw error;if(!(await authorized())){await db.auth.signOut();throw new Error('Этот аккаунт не указан в admin_users.');}$('#login-password').value='';await refreshAuth();}catch(err){alert(`Не удалось войти: ${err.message}`);}finally{btn.disabled=false;}});
  $('#logout').addEventListener('click',async()=>{await db.auth.signOut();$('#admin-panel').classList.add('admin-hidden');$('#login-panel').classList.remove('admin-hidden');});
  $('#product-reset').addEventListener('click',clearForm);
  $('#product-form').addEventListener('submit',async e=>{e.preventDefault();const btn=e.submitter;btn.disabled=true;message('#product-message','Сохраняем...');try{const id=$('#product-id').value,raw=$('#product-price').value.trim();const payload={category:$('#product-category').value,price:raw===''?null:Number(raw),available:$('#product-available').checked,active:$('#product-active').checked};for(const code of ['ar','en','ru']){payload[`name_${code}`]=$(`#name-${code}`).value.trim();payload[`description_${code}`]=$(`#description-${code}`).value.trim();}if(!payload.name_ar||!payload.name_en||!payload.name_ru)throw new Error('Заполните названия на трёх языках.');if(raw!==''&&(!Number.isFinite(payload.price)||payload.price<0))throw new Error('Проверьте цену.');const photo=$('#product-image').files[0];if(photo)payload.image_url=await uploadImage(photo,'products');const result=id?await db.from('products').update(payload).eq('id',id).select('id').single():await db.from('products').insert(payload).select('id').single();if(result.error)throw result.error;clearForm();await loadProducts();message('#product-message','Товар сохранён и опубликован.');}catch(err){message('#product-message',`Не удалось сохранить: ${err.message}`);}finally{btn.disabled=false;}});
  $('#owner-form').addEventListener('submit',async e=>{e.preventDefault();const btn=e.submitter;btn.disabled=true;message('#owner-message','Сохраняем...');try{const payload={id:1};for(const code of ['ar','en','ru'])payload[`owner_name_${code}`]=$(`#owner-${code}`).value.trim();const file=$('#owner-photo').files[0];if(file)payload.owner_photo_url=await uploadImage(file,'owner');const {error}=await db.from('site_settings').upsert(payload,{onConflict:'id'});if(error)throw error;await loadOwner();$('#owner-photo').value='';message('#owner-message','Профиль сохранён.');}catch(err){message('#owner-message',`Не удалось сохранить: ${err.message}`);}finally{btn.disabled=false;}});
  if(!cfg.supabaseUrl||!cfg.supabaseAnonKey){$('#admin-config-error').classList.remove('admin-hidden');$('#login-panel').classList.add('admin-hidden');return;}
  loadSdk().then(()=>{db=window.supabase.createClient(cfg.supabaseUrl,cfg.supabaseAnonKey);return refreshAuth();}).catch(e=>{$('#admin-config-error').classList.remove('admin-hidden');$('#admin-config-error').querySelector('p').textContent=e.message;$('#login-panel').classList.add('admin-hidden');});
})();
